### ISSUE TITLE
VS2017: Unexpected error while importing theme: System.Xml.XmlException

### ISSUE THREAD

**Issue by enemymaker** [strayiker/vs-theme-darcula#5]
When trying to import Darcula for into VS2015 or VS2017, I get following error:

> Microsoft Visual Studio
> ---------------------------
> Unexpected error while importing theme: System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
> 
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
>    at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
>    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
>    at System.Xml.XmlTextReaderImpl.Read()
>    at System.Xml.XsdValidatingReader.Read()
>    at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
>    at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
>    at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
>    at System.Xml.XmlDocument.Load(XmlReader reader)
>    at Microsoft.VisualStudio.Themes.Data.RegistryThemeIO.ReadThemeTemplatesFromXmlStream(Stream stream)
>    at Microsoft.VisualStudio.Themes.Designer.CommandHandlers.ImportTheme(ColorManager manager) 

Any idea what's wrong?
Microsoft supposes that there might be something wrong with the theme ...  (https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2017ColorThemeEditor#qna) 

Regards, and thanks a lot in advance!

**Comment by enemymaker** [comment]
For some reason my downloaded files became kind of corrupted during/after download.
I now cloned the git repo and successfully imported the theme in VS 2017.
